# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hyper_bench_vector <- function(xin, yin, N, n) {
    .Call('_EnrichR_hyper_bench_vector', PACKAGE = 'EnrichR', xin, yin, N, n)
}

name_table <- function(lh) {
    .Call('_EnrichR_name_table', PACKAGE = 'EnrichR', lh)
}

fast_factor <- function(x) {
    .Call('_EnrichR_fast_factor', PACKAGE = 'EnrichR', x)
}

sf <- function(x) {
    .Call('_EnrichR_sf', PACKAGE = 'EnrichR', x)
}

uniq <- function(xa) {
    .Call('_EnrichR_uniq', PACKAGE = 'EnrichR', xa)
}

